from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class Metrics(BaseModel):
    """Per-step LLM metrics (ATIF `MetricsSchema`)."""

    model_config = ConfigDict(extra="forbid")

    prompt_tokens: int | None = Field(
        default=None,
        description=(
            "All input tokens for this turn, including both cached and non-cached. "
            "`cached_tokens` is a subset of this count."
        ),
    )
    completion_tokens: int | None = Field(
        default=None,
        description="Tokens generated by the LLM response (reasoning + tool calls).",
    )
    cached_tokens: int | None = Field(
        default=None,
        description="Subset of `prompt_tokens` served from prompt cache.",
    )
    cost_usd: float | None = Field(
        default=None, description="Monetary cost of this step in USD."
    )
    prompt_token_ids: list[int] | None = Field(
        default=None,
        description="Integer token IDs for the prompt (v1.4+).",
    )
    completion_token_ids: list[int] | None = Field(
        default=None,
        description="Integer token IDs for the completion (v1.3+).",
    )
    logprobs: list[float] | None = Field(
        default=None,
        description="Per-completion-token log probabilities; aligns with `completion_token_ids`.",
    )
    extra: dict[str, Any] | None = Field(
        default=None,
        description="Provider-specific or experimental metrics (e.g. reasoning_tokens).",
    )
